"""
CockroachDB connection helper -- pilot only.

Reads the connection string from the COCKROACH_DATABASE_URL environment
variable so the real credential never has to live in code or git. Get the
connection string from the CockroachDB Cloud console ("Connect" button on
your cluster); it looks like:

    postgresql://<user>:<password>@<host>:26257/<database>?sslmode=verify-full

If you downloaded a CA cert (root.crt), append `&sslrootcert=<path-to-cert>`
to the string, or set it separately -- see connect_pg() below.

Requires `psycopg2-binary` (add it to requirements.txt / `pip install
psycopg2-binary`). This module raises a clear error if it's missing rather
than crashing the whole app on import, since it's not used by any live
request path yet.
"""
from __future__ import annotations

import os
import random
import time
from contextlib import contextmanager
from typing import Any, Callable, Iterator, TypeVar

try:
    import psycopg2
    import psycopg2.extras
except ImportError as exc:  # pragma: no cover - environment-dependent
    raise ImportError(
        "psycopg2-binary is required for the CockroachDB pilot code. "
        "Install it with: pip install psycopg2-binary"
    ) from exc

T = TypeVar("T")

ENV_VAR = "COCKROACH_DATABASE_URL"

# CockroachDB's "this transaction needs to be retried" error code. Not a
# bug -- it's the normal cost of CockroachDB's SERIALIZABLE-by-default
# concurrency model under contention. See designing-application-transactions.
SERIALIZATION_FAILURE = "40001"


def _connection_string() -> str:
    url = os.getenv(ENV_VAR, "").strip()
    if not url:
        raise RuntimeError(
            f"{ENV_VAR} is not set. Set it to your CockroachDB connection "
            "string (from the Cloud console's Connect button) before running "
            "any pilot code."
        )
    return url


@contextmanager
def pg_conn() -> Iterator["psycopg2.extensions.connection"]:
    """Yield a short-lived CockroachDB connection, closed on exit.

    Mirrors app.storage.db.db_conn()'s "always close, never leak" contract
    for the SQLite side of the app.
    """
    conn = psycopg2.connect(_connection_string())
    try:
        yield conn
    finally:
        conn.close()


def run_with_retry(work: Callable[["psycopg2.extensions.connection"], T], *, max_attempts: int = 5) -> T:
    """Run `work(conn)` inside a fresh connection, retrying on CockroachDB's
    40001 serialization-failure error with exponential backoff + jitter.

    For this pilot (single-row users writes) contention is very unlikely,
    but the retry loop is cheap insurance and is the documented correct
    pattern for CockroachDB client code.
    """
    backoff = 0.1
    last_exc: Exception | None = None
    for attempt in range(1, max_attempts + 1):
        try:
            with pg_conn() as conn:
                result = work(conn)
                conn.commit()
                return result
        except psycopg2.errors.lookup(SERIALIZATION_FAILURE) as exc:  # type: ignore[attr-defined]
            last_exc = exc
            if attempt == max_attempts:
                break
            time.sleep(backoff + random.uniform(0, 0.1))
            backoff = min(backoff * 2, 2.0)
    raise RuntimeError(f"CockroachDB transaction failed after {max_attempts} retries") from last_exc


def init_users_schema() -> None:
    """Create the pilot `users` table in CockroachDB if it doesn't exist yet.

    Safe to call repeatedly. Kept as a plain INT8 identity primary key
    (not UUID) on purpose: app.auth.dependencies puts the user id straight
    into the JWT `sub` claim as an int, and this table's write volume
    (occasional admin signups) is far too low for the sequential-id
    hotspot concern that UUIDs are meant to avoid to matter here.
    """
    with pg_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS users (
                    id             INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email          STRING NOT NULL UNIQUE,
                    password_hash  STRING NOT NULL,
                    password_salt  STRING NOT NULL,
                    display_name   STRING NOT NULL DEFAULT '',
                    role           STRING NOT NULL DEFAULT 'user',
                    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
                    last_login_at  TIMESTAMPTZ
                )
                """
            )
            cur.execute("CREATE INDEX IF NOT EXISTS idx_users_role ON users (role)")
        conn.commit()
