# generator

import pathlib

OUTPUT = pathlib.Path("tests/test_team_watcher_engine_props.py")

LINES = []
W = LINES.append

def NL():
    LINES.append("")

def section(title):
    LINES.append("")
    LINES.append(f"# {'-' * 75}")
    LINES.append(f"# {title}")
    LINES.append(f"# {'-' * 75}")
    LINES.append("")

# ============================================================
# Header
# ============================================================
W("# Feature: team-watcher-engine")
W('"""')
W("Property-based tests for the Team Watcher Prediction Engine.")
W("")
W("Each test class uses:")
W("  @settings(max_examples=100, suppress_health_check=[HealthCheck.too_slow])")
W('"""')
NL()
W("from __future__ import annotations")
NL()
W("import json")
W("import sqlite3")
W("import unittest")
W("from contextlib import contextmanager")
W("from unittest.mock import MagicMock, patch")
NL()
W("from hypothesis import HealthCheck, assume, given, settings")
W("from hypothesis import strategies as st")
NL()
W("import app.team_watcher_engine as twe")
W("from app.team_watcher_engine import (")
W("    _merge_signal,")
W("    _rules_model,")
W("    generate_weekly_analysis,")
W("    grade_tw_predictions,")
W("    init_tw_tables,")
W("    record_tw_prediction,")
W("    team_watcher_signal,")
W("    update_tw_weights,")
W(")")
NL()

# ============================================================
# Shared helpers
# ============================================================
section("Shared helpers")
W("def _make_mem_conn() -> sqlite3.Connection:")
W('    """In-memory SQLite with prerequisite tables for init_tw_tables."""')
W('    conn = sqlite3.connect(":memory:", check_same_thread=False)')
W("    conn.row_factory = sqlite3.Row")
W("    conn.execute(")
W('        """')
W("        CREATE TABLE IF NOT EXISTS ai_team_watchers (")
W("            team_key             TEXT NOT NULL PRIMARY KEY,")
W("            team_name            TEXT NOT NULL DEFAULT '',")
W("            profile_json         TEXT,")
W("            weekly_analysis_json TEXT DEFAULT '{}',")
W("            weekly_analysis_at   TEXT")
W("        )")
W('        """')
W("    )")
W("    conn.execute(")
W('        """')
W("        CREATE TABLE IF NOT EXISTS ai_team_watcher_matches (")
W("            team_key      TEXT NOT NULL,")
W("            match_id      TEXT NOT NULL,")
W("            match_date    TEXT,")
W("            goals_for     INTEGER,")
W("            goals_against INTEGER,")
W("            result        TEXT,")
W("            venue         TEXT,")
W("            created_at    TEXT NOT NULL DEFAULT current_timestamp,")
W("            PRIMARY KEY (team_key, match_id)")
W("        )")
W('        """')
W("    )")
W("    conn.commit()")
W("    init_tw_tables(conn)")
W("    return conn")
NL()
NL()
W("@contextmanager")
W("def _mem_db_ctx(conn: sqlite3.Connection, **_kwargs):")
W('    """Context-manager shim — yields shared in-memory connection."""')
W("    yield conn")
NL()

# ============================================================
# Hypothesis strategies
# ============================================================
section("Hypothesis strategies")
W("def _valid_profile_strategy(sample_size_st=st.integers(min_value=5, max_value=50)):")
W('    """Build a valid Team_Profile dict."""')
W("    return st.builds(")
W("        dict,")
W("        sample_size=sample_size_st,")
W("        win_rate=st.floats(min_value=0.0, max_value=1.0, allow_nan=False),")
W("        btts_rate=st.floats(min_value=0.0, max_value=1.0, allow_nan=False),")
W("        over_25_rate=st.floats(min_value=0.0, max_value=1.0, allow_nan=False),")
W("        clean_sheet_rate=st.floats(min_value=0.0, max_value=1.0, allow_nan=False),")
W("        goals_for_avg=st.floats(min_value=0.0, max_value=5.0, allow_nan=False),")
W("        goals_against_avg=st.floats(min_value=0.0, max_value=5.0, allow_nan=False),")
W("        venue_split=st.just({}),")
W("    )")
NL()
NL()
W("def _match_row_strategy():")
W('    """Build a single finished match row dict."""')
W("    return st.fixed_dictionaries({")
W('        "goals_for": st.integers(min_value=0, max_value=10),')
W('        "goals_against": st.integers(min_value=0, max_value=10),')
W('        "result": st.sampled_from(["win", "draw", "loss"]),')
W('        "venue": st.sampled_from(["home", "away"]),')
W('        "match_date": st.just("2025-01-15"),')
W("    })")
NL()

OUTPUT.write_text("\n".join(LINES), encoding="utf-8")
print("header + helpers written:", OUTPUT.stat().st_size, "bytes")
