# noqa: F401  # DEPRECATED shim — see migration_checklist.md
from app.scheduling.scheduler import *  # noqa: F401,F403
from app.scheduling.scheduler import (  # noqa: F401
    LIVE_PRIORITY_ENGINE_ID,
    UNIFIED_UPCOMING_BATCH_SIZE,
    SCHEDULER_INTERVAL_DEFAULTS,
    job_ingest_upcoming,
    job_ingest_live,
    job_enrich_worker,
    job_live_priority,
    get_live_priority_mode,
    set_live_priority_mode,
    job_live_priority_toggle,
    scheduler_intervals,
    patch_scheduler_intervals,
    reset_scheduler_intervals,
    job_sofa_pipeline,
    job_enrich_future,
    job_unified_upcoming,
    job_unified_live,
    job_competition_special,
    job_archive_finished,
    job_flush_to_mongo,
    job_grade_predictions,
    job_grade_overdue_predictions,
    job_prune_mongo,
    job_keep_alive,
    job_system_supervisor,
    job_prediction_monitor,
    job_autopilot_guardian,
    start_scheduler,
    stop_scheduler,
    scheduler_status,
    is_shutting_down,
    run_job_with_guard,
)
